MOMMY_CAPITALIZE=0
MOMMY_ENCOURAGEMENTS=0
MOMMY_FORBIDDEN_WORDS="big fat kiss"
MOMMY_PRONOUNS="she her her"
MOMMY_SUFFIX="~/ :3/ <3"

MOMMY_COMPLIMENTS_EXTRA="you're being such a good girl" # TODO: add more
