iosevka: &iosevka IosevkaTerm Nerd Font:style=solid:pixelsize=16
firacode: &firacode FiraCode Nerd Font:style=solid:pixelsize=16

bar:
  height: 24
  location: bottom
  spacing: 5
  margin: 7

  # Default font
  font: *iosevka

  foreground: cad3f5ff
  background: 24273acc

  border:
    width: 1
    color: 00000000
    margin: 6
    top-margin: 0

  right:
    - battery:
        name: BAT1
        poll-interval: 3000
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff, font: *firacode, right-margin: 8}
                      - string: {text:  , foreground: ffa600ff, font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , font: *firacode, right-margin: 8}
                      - string: {text:  , foreground: a6da95ff, font: *firacode, right-margin: 8}
                - string: {text: "[{capacity}%]", font: *iosevka}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text:   , foreground: a6da95ff, font: *firacode, right-margin: 8}
                - string: {text: "[{capacity}%]", font: *iosevka}
              state == full:
                - string: {text:   , foreground: a6da95ff, font: *firacode, right-margin: 8}
                - string: {text: "[Full]", font: *iosevka}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff, font: *firacode}
                      - string: {text:  , foreground: ffa600ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                      - string: {text:  , foreground: a6da95ff, font: *firacode}
                - string: {text: "{capacity}%", font: *iosevka}
    - clock:
        time-format: "%I:%M"
        content:
          - string: {text:  , font: *iosevka}
          - string: {text: "[{time}] "}
          - string: {text:  , font: *iosevka}
          - string: {text: "[{date}] ", right-margin: 3}